dist: bionic

language: generic

install:

  # Install GNAT FSF
  - sudo apt-get -y install gnat gprbuild xmlada

  # Install lcov for coverage
  - sudo apt-get -y install lcov

script:
  - ./configure --enable-coverage
  - make run
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f util.cov
